CKAN 2.9 fixes
ckan/ckanext-xloader pull request #110
Opened 2020-07-30 08:55 UTC by amercader

This includes two 2.9 fixes (it does not include python 3 support related changes)

Commit messages have all details but the summary is:

1. Pass ignore_auth on action calls
2. Refactor plugin interfaces to avoid transaction error (Same as  ckan/ckan#5173)

2020-09-01 12:55 UTC, kowh-ai commented
**FYI:** I have tested @smotornyuk 's Python3 Support PR: https://github.com/ckan/ckanext-xloader/pull/113 and had problems with both CKAN and the ckanext-xloader extension **until** I applied the fixes from this PR. After I made these changes it worked fine

2021-04-07 23:35 UTC, ThrawnCA requested changes

2021-04-07 23:35 UTC, ThrawnCA commented on ckanext/xloader/plugin.py
> +            log.debug('Skipping xloading resource {id} because '
This should use parameterised logging instead of `format`.

2021-04-07 23:35 UTC, ThrawnCA commented on ckanext/xloader/plugin.py
> +            log.debug('Submitting resource {0} to be xloadered'
Should use parameterised logging.

2021-04-08 00:00 UTC, ThrawnCA commented on ckanext/xloader/plugin.py
> +    # IResourceController
These could merge with the block starting at line 56.

2021-04-08 00:00 UTC, ThrawnCA commented on ckanext/xloader/jobs.py
> +    context = {'ignore_auth': True}
This is out of date; latest code loads an actual account.

2021-09-22 10:49 UTC, merged