SQLAlchemy v2 support
ckan/ckanext-xloader pull request #225
Opened 2024-09-10 17:03 UTC by smotornyuk

Compatibility with the new SQLAlchemy version tested against [this PR](https://github.com/ckan/ckan/pull/8410).

2024-09-10 20:31 UTC, duttonw commented
Looks like setup tools for 2.9 has started to fail unrelated to your changes. 


      /usr/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'

2024-09-10 23:20 UTC, ThrawnCA commented
> Looks like setup tools for 2.9 has started to fail unrelated to your changes.

We can fix that, but I'll note that with the release of CKAN 2.11, 2.9 is no longer officially supported: https://ckan.org/blog/the-new-ckan-211-release-is-now-available

2024-09-10 23:27 UTC, ThrawnCA commented
Looks like 2.9 isn't compatible with the newer SQLAlchemy. We should probably make version-specific requirements files.

2024-10-15 04:58 UTC, duttonw commented
I've cut a release today for 1.2.0 which is compatible for 2.9 ~ 2.11. 

I'm ok with dropping 2.9 support via this PR, I've updated the doc's and cicd pipeline accordingly. 

I'd like to pull in the last pieces of work from the qld-gov-au fork prior to this being included for one last 1.x.x release.

As this is major breaking change, it should bump to 2.0.0 on this being merged into master/released.

2024-10-15 06:58 UTC, ThrawnCA approved these changes

2024-11-21 06:29 UTC, ThrawnCA approved these changes

2024-12-10 00:11 UTC, ThrawnCA requested changes

2024-12-10 00:11 UTC, ThrawnCA commented on .github/workflows/publish.yml
> -          - ckan-version: "2.9"
Still needs to be removed from the test workflow.

2024-12-10 00:19 UTC, ThrawnCA approved these changes

2024-12-10 00:46 UTC, merged